# Generated by Django 5.0.1 on 2024-01-15 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usr_subs',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subs',
        ),
        migrations.AddField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
