# Generated by Django 5.0.1 on 2024-01-16 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_usr_subs_alter_profile_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='user_pics', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
